version: '3'
services:
  base:
    image: "mysql"
    container_name: 'MYSQL_Base'
    environment:
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - base_mysql:/var/lib/mysql      
    ports:
      - "3306:3306"
    restart: always

  backend:
    image: 'backendimg_proy1'
    container_name: 'backend_proy1'
    privileged: true
    volumes:
      - type: bind
        source: /proc
        target: /proc
    environment:
      DB_USER: root
      DB_PASSWORD: secret
      DB_HOST: MYSQL_Base
      DB_PORT: 3306
      DB_NAME: Proyecto1
    ports:
      - "5200:5200"
    restart: always
  fronted:
    image: 'frontedimg_proy1'
    container_name: 'fronted_proy1'
    ports:
      - "80:80"
    restart: always
    

volumes:
  base_mysql: