# Usa una imagen base de Node.js
FROM node:18.18.1-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los archivos del proyecto al contenedor
COPY . .

# Instala las dependencias del proyecto
RUN npm install

# Expone el puerto en el que la API estará escuchando
EXPOSE 5000

# Comando para ejecutar la aplicación cuando el contenedor se inicia
CMD ["node", "src/index.js"]