# Usa la imagen oficial de Golang como base
FROM golang:latest

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /go/src/app

# Copia los archivos del cliente a la imagen
COPY . .

# Compila el código Go
RUN go build -o main .

# Expone el puerto necesario
EXPOSE 3000

# Comando para ejecutar la aplicación cuando se inicie el contenedor
CMD ["./main"]